# -*- coding: utf-8 -*-
"""Algoritmo_de_Cifrado_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11p6bAg41l34kauWRwX9qrQXg4w3uq_HR

# Algoritmo 4
Algoritmo que realice el cifrado de una cadena de caracteres mediante un método de sustitución Monoalfabético de desplazamiento n caracteres a la derecha. Tanto la palabra como el valor de n se ingresan al iniciar el algoritmo. El algoritmo debe mostrar el alfabeto original, el alfabeto cifrado, la cadena de caracteres ingresada y su resultado.
"""

def cifrado_monoalfabetico(texto, desplazamiento):
    abecedario = 'abcdefghijklmnñopqrstuvwxyzABCDEFGHIJKLMNÑOPQRSTUVWXYZ'
    resultado = ''
    if desplazamiento > 0 :
      for caracter in texto:
          if caracter in abecedario:
              indice = (abecedario.index(caracter) + desplazamiento) % len(abecedario)
              resultado += abecedario[indice]
          else:
              resultado += caracter
      return resultado
    else:
      resultado = 'Error, Desplazamiento negativo, no se puede ejecutar'
      return resultado


palabra = input("Ingrese la palabra a cifrar: ")
desplazamiento = int(input("Ingrese el valor de desplazamiento: "))



if desplazamiento > 0:
  print("abecedario original:", 'abcdefghijklmnñopqrstuvwxyzABCDEFGHIJKLMNÑOPQRSTUVWXYZ')
  print("abecedario cifrado:", cifrado_monoalfabetico('abcdefghijklmnñopqrstuvwxyzABCDEFGHIJKLMNÑOPQRSTUVWXYZ', desplazamiento))
  print("Texto original:", palabra)
  print("Texto cifrado:", cifrado_monoalfabetico(palabra, desplazamiento))
else:
  print("No se puede ejecutar, el desplazamiento es negativo.")